// File generated by FlutterFire CLI & customized for MoneyMateX

// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show kIsWeb;

/// Default [FirebaseOptions] for use with Firebase SDKs.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    throw UnsupportedError(
      'FirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz8z7G9ZH9VVvgDNtn8R0vT2L5SwlxsuM',
    authDomain: 'moneymatex-kathir.firebaseapp.com',
    projectId: 'moneymatex-kathir',
    storageBucket: 'moneymatex-kathir.firebasestorage.app',
    messagingSenderId: '163215880560',
    appId: '1:163215880560:web:c86fa5142a867bad1a1fb5',
    measurementId: 'G-P9MK65RVV2',
  );
}